### ISSUE TITLE
Discussion: What panes/fields should exist for the Tripal 3 organism layout?

### ISSUE THREAD

**Issue by bradfordcondon** [NAL-i5K/tripal3_organism_layout#1]
see: https://i5k.nal.usda.gov/Cimex_lectularius

Overview:  Remove all the chado field display stuff.  Anything that might be useful stick in a seperate, not open by default field.

The other left-panels are all outlinks, either to other analyses or to dbxrefs.  I therefore will make two tabs, one called "external links" and one called "Annotation and Assembly" which will link out to dbxrefs and Analysis methods, respectively.

Assembly info and stats: these are all chado fields/props, and For now I propose putting them in a "assembly details" pane on hte left.  Looking at your code though I think that this info is not stored in chado but in a custom DB, so i will perhaps have to import your fields into my site first.

Data Files : This could be a field, or this could continue to be a block.  I think we'll address later since although we're adding file fields, they wont be organized.  Maybe worth porting all components of your all's file browser and display into a tripal module that attaches vi a field?

**Comment by mpoelchau** [comment]
Finished T3 migration, closing.
